### ISSUE TITLE
redos vulnerability

### ISSUE THREAD

**Issue by andeanfog** [samclarke/robots-parser#12]
## Repro steps
```javascript
const robotsParser = require('robots-parser');
const r = robotsParser('https://localhost/robots.txt', [
  'User-agent: * ',
  'Allow: **************************.js*',
].join('\n'));

r.isAllowed('https://localhost/index.html', 'bot name');
```

This takes a long time to parse.
Adding more expressions or making the URL longer makes it take more time as well.

**Comment by andeanfog** [comment]
Workaround is to collapse sequences of consecutive asterisks into one character.

**Comment by samclarke** [comment]
Fixed and new version released. Thanks for reporting!
