### ISSUE TITLE
Support for ignoring protocols and ports

### ISSUE THREAD

**Issue by ColinRoberts** [samclarke/robots-parser#14]
Hi,

The below code outputs _false_ then _true_, because the first parser is created with a URL that uses the HTTP protocol, and the second one with HTTPS.

```
var robotsParser = require("robots-parser");

var robots1 = robotsParser('http://www.example.com/robots.txt', ["User-agent: *", "Disallow:"].join("\n"));
var robots2 = robotsParser('https://www.example.com/robots.txt', ["User-agent: *", "Disallow:"].join("\n"));

console.log(robots1.isDisallowed("http://www.example.com/test", "useragent"));
console.log(robots2.isDisallowed("http://www.example.com/test", "useragent"));
```

I understand that based on specifications a robots.txt file is only valid for URLs with the same protocol, host, and port. However, this is hugely inconvenient for programs that are trying to use this module for crawling websites with links that occasionally swap between HTTP and HTTPS. 

Should there not be an option to ignore lines 325-330 in Robots.js, or at least limit it to only checking the URL's hostname and (or) port? It otherwise makes this module useless for people who are dealing with websites that swap protocols and don't want to take on the inefficiency of needlessly parsing the same robots.txt file twice, for HTTP and HTTPS.

**Comment by ColinRoberts** [comment]
Or maybe lines 325-330 make sense for isAllowed(), but not for isDisallowed?

**Comment by samclarke** [comment]
I've added support for relative URLs (only allowed if the robots.txt URL and all URLs being check are relative) so that applications can handle checking and relaxing the protocol, host and port matching if desired.
