### ISSUE TITLE
Need help maintain this project?

### ISSUE THREAD

**Issue by AnandChowdhary** [samclarke/robots-parser#18]
Hi @samclarke, I noticed that there are some issues and PRs open, perhaps you didn't get around to reviewing them.

If you like, I'd love to help you maintain this project by reviewing the PRs, adding TypeScript support, more comprehensive tests for different Node versions, and setting up community health files to encourage future contributions.

Although it's just a small file you wrote several years ago, `robots-parser` has 300k+ downloads per week, so it would be nice to have some systems in place to update (dev) dependencies and ensure project maintenance. What say? You can add me as a repository collaborator and I'll get started! 😄

**Comment by hjr3** [comment]
We can add TypeScript support via DefinitelyTyped. That would help people and not require repository access.

**Comment by samclarke** [comment]
Sorry for my slow reply, that would be great! I've invited you as a contributor.
