### ISSUE TITLE
Returns true for disallowed route

### ISSUE THREAD

**Issue by david2am** [samclarke/robots-parser#21]
Hey nice project, recently I started to use it on my personal ones but I get this:
```
var robotsParser = require('robots-parser');

var robots = robotsParser('http://www.example.com/robots.txt', [
	'User-agent: *',
	'Disallow: /dir/',
	'Disallow: /test.html',
	'Allow: /dir/test.html',
	'Allow: /test.html',
	'Crawl-delay: 1',
	'Sitemap: http://example.com/sitemap.xml',
	'Host: example.com'
].join('\n'));

console.log(robots.isAllowed('http://www.example.com/test.html', 'Sams-Bot/1.0')); // false

```
When I run ``` node myParserFile.js``` console.log returns **true**

**Comment by samclarke** [comment]
Thanks for reporting! The result is correct, it's a bug in the README. 

This library follows the same order of precedence as [Googles implementation](https://developers.google.com/search/docs/advanced/robots/robots_txt#order-of-precedence-for-rules) and the [draft spec](https://datatracker.ietf.org/doc/html/draft-koster-rep-00#section-2.2.2) which now state if the allow and disallow rules are equal the allow rule wins.

It used to be undefined so previous versions of this library would use the first matching rule. I forgot to update the README when updating the code to the latest spec changes.
