### ISSUE TITLE
Empty 'Disallow:' statement incorrectly gobbles the next statement

### ISSUE THREAD

**Issue by skibum3d** [samclarke/robots-parser#32]
For a robots.txt file like the following:

`User-agent: *
Disallow:

Sitemap: https://www.site.com/sitemap_index.xml
`

The robots-parser library seems to take the next non-empty line after an empty Disallow, leading to the following parsed output:

`
Robots {
  _url: URL {
    href: 'user-agent: *Disallow:Sitemap: https://www.site.com/sitemap_index.xml',
    origin: 'null',
    protocol: 'user-agent:',
    username: '',
    password: '',
    host: '',
    hostname: '',
    port: '',
    pathname: ' *Disallow:Sitemap: https://www.site.com/sitemap_index.xml',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  _rules: [Object: null prototype] {},
  _sitemaps: [],
  _preferredHost: null
}
`

I believe an empty `Disallow:` line is supported in the spec by this ABNF:
`rule = *WS ("allow" / "disallow") *WS ":"
*WS (path-pattern / empty-pattern) EOL`

**Comment by samclarke** [comment]
Thanks for reporting. It should correctly handle empty disallow statements. From the output, it looks like it's parsing the contents as the URL of the robots.txt file.

Could the first argument be missing? It should be the URL of the robots.txt file, something like:

```js
// Full URL or just /robots.txt if doing relative matching
const robots = robotsParser('https://www.site.com/robots.txt', `User-agent: *
Disallow:

Sitemap: https://www.site.com/sitemap_index.xml
`);
```

**Comment by skibum3d** [comment]
Thanks Sam, you're correct that the first argument is missing, and with that corrected everything parses as expected.
