### ISSUE TITLE
RFC update

### ISSUE THREAD

**Issue by joepie91** [samclarke/robots-parser#37]
Hi, just a heads-up - the README states that this library implements an older draft of the RFC. Since then, a proposed final(?) version has been published: https://datatracker.ietf.org/doc/html/rfc9309

I'm not sure if anything has changed since the draft you implemented, but I figured you might want to at least update the README (and the one on npm) if not, so that people can more easily find this library when looking for the RFC number :)

**Comment by samclarke** [comment]
Thanks for reporting!

Looking at the diff, the only changes look to be with improving clarity and changing it from a draft so this should be compliant with it. I'll get the README updated.
